server {
    listen 8089;
    root ./www;
}

so create a function called assignValue that will get the std::vector<std::string> something, find the keyword and assign the value to our structs.



like



liten 8089



will will find listen, then add + 1 on index (logically) atoi the 8089 and assign to the correct struct variable. 