server {
    listen 8089;
    listen 8090;
    listen 8091;

    server_name localhost;

    client_max_body_size 1000000;

    error_page 404 ./var/errors/404.html;
    error_page 403 ./var/errors/403.html;
    error_page 500 ./var/errors/500.html;

    location / {
        allowed_methods GET HEAD;
        root ./var/www;
        index /index.html;
        autoindex off;
    }

    location /images {
        allowed_methods GET POST;
        root ./var/assets;
        autoindex on;
    }

    location /uploads {
        allowed_methods GET POST DELETE HEAD;
        root ./var;
        upload_store /uploads;
        upload_enabled on;
        autoindex on;
    }

    location /autoindexon {
		allowed_methods GET;
        root ./var;
        autoindex on;
    }

    location /autoindexoff {
		allowed_methods GET;
        root ./var;
    }

    location /old-page {
        allowed_methods GET;
        redirect /new-page;
    }

    location /cgi-bin {
        allowed_methods GET POST;
        root ./var;
		autoindex on;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
        cgi .sh /usr/bin/bash;
    }
}
