server {
    listen 8089;
    listen 8090;
    listen 8091;

    location / {
        root ./var/www;
        index /index.html;
        upload_store /uploads;
        allowed_methods GET POST;
    }

    location /favicon.ico {
        root ./var/www/assets;
        allowed_methods GET;
    }

    location /autoindexoff {
        root ./var/www;
        allowed_methods GET;
    }

    location /autoindexon {
        root ./var/www;
        autoindex on;
        allowed_methods GET;
    }

    location /scripts {
        root ./var/www;
    }

    location /styles.css {
        root ./var/www;
    }

    location /upload {
        root ./var/www;
        upload_store /uploads;
    }

    location /delete {
        root ./var/www/uploads;
        allowed_methods DELETE;
    }

}
