server {
    listen 8089;
    listen 8090;
    listen 8091;

    location / {
        root ./var/www;
        index /index.html;
        allowed_methods GET;
    }

    location /favicon.ico {
        root ./var/www/asset;
        allowed_methods GET;
    }

    location /notauthorized {
        root ./var/www;
        allowed_methods GET;
    }

    location /authorized {
        root ./var/www;
        autoindex on;
        allowed_methods GET;
    }

    location /scripts {
        root ./var/www;
    }

    location /styles.css {
        root ./var/www;
    }

    location /upload {
        root ./var/www;
        upload_store /uploads;
    }

    location /delete {
        root ./var/www;
        upload_store /uploads;
    }

}
