server {
	listen 8888;
	server_name localhost;
	client_max_body_size 100;

	location / {
		allowed_methods GET;
		root ./var/www;
		index /index.html;
	}

	location /directory {
		allowed_methods GET POST;
		alias ./YoupiBanane;
		index /youpi.bad_extension;
		cgi .bla /cgi_tester;
	}

	location /post_body {
		allowed_methods POST;
		root ./var/www;
	}
}
